language: java
jdk: oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
    - ./gradlew clean
    - ./gradlew build
#    - ./gradlew uploadArchives

env:
  global:
  - secure: A2L5EprUrhoYOTv/3/cABmKY32P+w+lKT2WhpFVwH2s5cVgmqu86nGx4qJ4gmPvTH5yreUAqmqpYzl8IoC6rV5mcwmTJG8Yjked0XcylDuV1YerVLA8ZHcoKn7yWPZ3KKyY9ocL7nv30Mjhzuow7x0PMIPzwivWoKZGMqHHGEeN8biro/jTcoWHeoCD9JaAd62xYT2+INnRfeKA+nsnqopQanDmNuMBEVfKBTZMzHig5xmKKea3zoUvZw4+dCw/nU2eAoeBncLbIKGA7HUpFvgsOD9mW9sE7p1KQb+mnflCFCD/g4LhgJ4YdxDvqoQTXWl9qc65Q2fSbBeaZTF6EIoAouSo/o23kebdsdCWP+vrxCzNAIwwklh3+imJPYM8JS5Py6FKaoNGXchjkHQs1n7+vFov8HackcTsad0HWPoH77bwgm9KtizKw5gw5BvX7w+o0ebXfeYT5/xUD5dLTeJxyepN2N//G47HQQYW3Ipe7IpYxkykmgFgErNGIivkaNAZrfaH+mX2FAJFaEXHFJDHn3kHMj35eWL3no6maWLNcxoSbaD06r3h0195N3ffGo1x2F9mqLzwBM+BeVcQazRBbtFheh5obPV5FetdQuDyIZ92keQYGFXyWiDjfarnPQfHEjwt5f8gi/eWYtHeQceUNi1lW6BcJslMDB1G5JQE=
  - secure: kdN+6T8sKA9/J77H0FvOtskKrwchC42fX+BtNS3u6uBFgc5SW0Tqw4tSuoqJzQO72QapRhu5LYi2fY7uiza6nws3i459Auj8AeEdcCNf4zdLBcuEPLT2xLbHm/D9mErT0DIRkedJQ5mGUPRXEwkL/tNIsrcRq3HeRInTPENTfot/MyDP6rjxwP8hg8qAbMAbHsgifEmlLH7WXXSMCeFR/Esdy+giXKM9ZuZ3p5L7qIuDWlSOQ2mA10g5olzIGe54kxr4YootjcP7iZiMFhPdU5NAi5jBYkhR1rrShBF6/uu3PSk25PZI9C5wlhg2zWcTrN0s4/qBw+jvUcIlmP76xZIpxNCDsgMEfzmVWRgJZ86k6VdYo79PY7QlY9aN01Q3kBl0DHkJyuhYFip2Z8P/Sl5e+AEi4unkOrFkW8M+vVkBNoCaN8YqZq5sRtIvR/ek2nYxRuIoPoT/PDdrdiBU/aj/kr+JIFiHsSXVb/lVEYyNr+poe5m6n1vMMHLvbumssgfLjgxkwjdZL9TYxjBpKWl+xKLB9/DLc6xQkDzzS4dOSryoOdq38zQslkrtYmu0cbZqgA3vjdvduFtJkwShSFQ01fjYHesS2oSka6RR94QgYOyflLT43KKpSBenmtxthy/ua9UQzeJp0SNP8cn4D9VyepfTmkD5HXe7VzwvusY=
